/*
 * Copyright (c) 2019 Abex
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.api;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum Quest
{
	//Free Quests
	BLACK_KNIGHTS_FORTRESS(299),
	COOKS_ASSISTANT(300),
	THE_CORSAIR_CURSE(301),
	DEMON_SLAYER(302),
	DORICS_QUEST(303),
	DRAGON_SLAYER(304),
	ERNEST_THE_CHICKEN(305),
	GOBLIN_DIPLOMACY(306),
	IMP_CATCHER(307),
	THE_KNIGHTS_SWORD(308),
	MISTHALIN_MYSTERY(309),
	PIRATES_TREASURE(310),
	PRINCE_ALI_RESCUE(311),
	THE_RESTLESS_GHOST(312),
	ROMEO__JULIET(313),
	RUNE_MYSTERIES(314),
	SHEEP_SHEARER(315),
	SHIELD_OF_ARRAV(316),
	VAMPIRE_SLAYER(317),
	WITCHS_POTION(318),

	//Members' Quests
	ANIMAL_MAGNETISM(331),
	ANOTHER_SLICE_OF_HAM(332),
	BETWEEN_A_ROCK(333),
	BIG_CHOMPY_BIRD_HUNTING(334),
	BIOHAZARD(335),
	CABIN_FEVER(336),
	CLOCK_TOWER(337),
	COLD_WAR(338),
	CONTACT(339),
	CREATURE_OF_FENKENSTRAIN(340),
	DARKNESS_OF_HALLOWVALE(341),
	DEATH_PLATEAU(342),
	DEATH_TO_THE_DORGESHUUN(343),
	THE_DEPTHS_OF_DESPAIR(344),
	DESERT_TREASURE(345),
	DEVIOUS_MINDS(346),
	THE_DIG_SITE(347),
	DRAGON_SLAYER_II(348),
	DREAM_MENTOR(349),
	DRUIDIC_RITUAL(350),
	DWARF_CANNON(351),
	EADGARS_RUSE(352),
	EAGLES_PEAK(353),
	ELEMENTAL_WORKSHOP_I(354),
	ELEMENTAL_WORKSHOP_II(355),
	ENAKHRAS_LAMENT(356),
	ENLIGHTENED_JOURNEY(357),
	THE_EYES_OF_GLOUPHRIE(358),
	FAIRYTALE_I__GROWING_PAINS(359),
	FAIRYTALE_II__CURE_A_QUEEN(360),
	FAMILY_CREST(361),
	THE_FEUD(362),
	FIGHT_ARENA(363),
	FISHING_CONTEST(364),
	FORGETTABLE_TALE(365),
	BONE_VOYAGE(366),
	THE_FREMENNIK_ISLES(367),
	THE_FREMENNIK_TRIALS(368),
	GARDEN_OF_TRANQUILLITY(369),
	GERTRUDES_CAT(370),
	GHOSTS_AHOY(371),
	THE_GIANT_DWARF(372),
	THE_GOLEM(373),
	THE_GRAND_TREE(374),
	THE_GREAT_BRAIN_ROBBERY(375),
	GRIM_TALES(376),
	THE_HAND_IN_THE_SAND(377),
	HAUNTED_MINE(378),
	HAZEEL_CULT(379),
	HEROES_QUEST(380),
	HOLY_GRAIL(381),
	HORROR_FROM_THE_DEEP(382),
	ICTHLARINS_LITTLE_HELPER(383),
	IN_AID_OF_THE_MYREQUE(384),
	IN_SEARCH_OF_THE_MYREQUE(385),
	JUNGLE_POTION(386),
	KINGS_RANSOM(387),
	LEGENDS_QUEST(388),
	LOST_CITY(389),
	THE_LOST_TRIBE(390),
	LUNAR_DIPLOMACY(391),
	MAKING_FRIENDS_WITH_MY_ARM(392),
	MAKING_HISTORY(393),
	MERLINS_CRYSTAL(394),
	MONKEY_MADNESS_I(395),
	MONKEY_MADNESS_II(396),
	MONKS_FRIEND(397),
	MOUNTAIN_DAUGHTER(398),
	MOURNINGS_ENDS_PART_I(399),
	MOURNINGS_ENDS_PART_II(400),
	MURDER_MYSTERY(401),
	MY_ARMS_BIG_ADVENTURE(402),
	NATURE_SPIRIT(403),
	OBSERVATORY_QUEST(404),
	OLAFS_QUEST(405),
	ONE_SMALL_FAVOUR(406),
	PLAGUE_CITY(407),
	PRIEST_IN_PERIL(408),
	THE_QUEEN_OF_THIEVES(409),
	RAG_AND_BONE_MAN(410),
	RAG_AND_BONE_MAN_II(411),
	RATCATCHERS(412),
	RECIPE_FOR_DISASTER(413),
	RECRUITMENT_DRIVE(414),
	REGICIDE(415),
	ROVING_ELVES(416),
	ROYAL_TROUBLE(417),
	RUM_DEAL(418),
	SCORPION_CATCHER(419),
	SEA_SLUG(420),
	SHADES_OF_MORTTON(421),
	SHADOW_OF_THE_STORM(422),
	SHEEP_HERDER(423),
	SHILO_VILLAGE(424),
	THE_SLUG_MENACE(425),
	A_SOULS_BANE(426),
	SPIRITS_OF_THE_ELID(427),
	SWAN_SONG(428),
	TAI_BWO_WANNAI_TRIO(429),
	A_TAIL_OF_TWO_CATS(430),
	TALE_OF_THE_RIGHTEOUS(431),
	A_TASTE_OF_HOPE(432),
	TEARS_OF_GUTHIX(433),
	TEMPLE_OF_IKOV(434),
	THRONE_OF_MISCELLANIA(435),
	THE_TOURIST_TRAP(436),
	TOWER_OF_LIFE(437),
	TREE_GNOME_VILLAGE(438),
	TRIBAL_TOTEM(439),
	TROLL_ROMANCE(440),
	TROLL_STRONGHOLD(441),
	UNDERGROUND_PASS(442),
	CLIENT_OF_KOUREND(443),
	WANTED(444),
	WATCHTOWER(445),
	WATERFALL_QUEST(446),
	WHAT_LIES_BELOW(447),
	WITCHS_HOUSE(448),
	ZOGRE_FLESH_EATERS(449),

	//Miniquests
	ENTER_THE_ABYSS(319),
	ARCHITECTURAL_ALLIANCE(320),
	BEAR_YOUR_SOUL(321),
	ALFRED_GRIMHANDS_BARCRAWL(322),
	CURSE_OF_THE_EMPTY_LORD(323),
	ENCHANTED_KEY(324),
	THE_GENERALS_SHADOW(325),
	SKIPPY_AND_THE_MOGRES(326),
	THE_MAGE_ARENA(327),
	LAIR_OF_TARN_RAZORLOR(328),
	FAMILY_PEST(329),
	THE_MAGE_ARENA_II(330);

	@Getter
	private final int id;

	public QuestState getState(Client client)
	{
		client.runScript(ScriptID.QUESTLIST_PROGRESS, id);
		switch (client.getIntStack()[0])
		{
			case 2:
				return QuestState.FINISHED;
			case 1:
				return QuestState.NOT_STARTED;
			default:
				return QuestState.IN_PROGRESS;
		}
	}
}
